# Generated by Django 4.1.1 on 2022-09-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_provider',
            old_name='user_name',
            new_name='email',
        ),
    ]
