# Generated by Django 4.1.1 on 2022-10-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
