# Generated by Django 4.1.1 on 2022-10-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_order_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(max_length=250)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
