# Generated by Django 4.1.1 on 2022-10-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_remove_chat_service_id_chat_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
