# Generated by Django 4.1.3 on 2022-11-20 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_chat_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soil_test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('user_id', models.IntegerField()),
                ('comment', models.CharField(max_length=250)),
                ('service_provider', models.CharField(max_length=50)),
                ('service_provider_id', models.IntegerField()),
                ('status', models.CharField(max_length=20)),
                ('date', models.CharField(max_length=250)),
            ],
        ),
    ]
